language: php

php:
    - 7.0

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.0
          env: SYMFONY_VERSION=2.8.*
        - php: 7.0
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: SYMFONY_VERSION=4.0.*

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
